name: push to mk8s

on: [push]

jobs:
  deploy:
    name: deploy to mk8s
    runs-on: ubuntu-latest
    steps:
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: MYKUBECONFIG
        id: setcontext
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0' # default is latest stable
        id: install
      - uses: Azure/k8s-deploy@v1.3
        with:
          manifests: |
            manifests/nginx-deployment.yaml
          kubectl-version: 'v1.20.0'
        id: deploy