name: push to mk8s

on: [push]

jobs:
  deploy:
    name: deploy to mk8s
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0' # default is latest stable
        id: install             
      - uses: azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.MYKUBECONFIG }}
          context: microk8s
        id: setcontext               
      - uses: Azure/k8s-deploy@v1.2
        with:
          manifests: |
            deployment.yaml  
          action: deploy
        id: deploy