# This is a basic workflow to help you get started with Actions

name: GUIdeploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]


  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          kubeconfig: MYKUBECONFIG

      - name: kubectl get
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.20.0' # default is latest stable

      - name: Deploy to Kubernetes cluster
        uses: Azure/k8s-deploy@v1.3
        with:
          # Choose the target Kubernetes namespace. If the namespace is not provided, the commands will run in the default namespace.
          namespace: default
          # Path to the manifest files which will be used for deployment.
          manifests: deployment.yaml
          kubectl-version: 'v1.20.0'
          action: deploy
          # Deploy when a previous deployment already exists. If true then --force argument is added to the apply command
          force: '--force'
